name: linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cxx: [g++-9, g++-10, g++-11, clang++-10, clang++-11, clang++-12]
        build_type: [Debug, Release]
        std: [17, 20]
        os: [ubuntu-20.04]
        exclude:
          # Temporarily exclude GCC10 due to ICE
          - cxx: g++-10
        include:
          # GCC8 and Clang 9 on Ubuntu 18.04
          - cxx: g++-8
            std: 17
            build_type: Debug
            install: sudo apt install g++-8
            os: ubuntu-18.04
          - cxx: clang++-9
            std: 17
            build_type: Debug
            os: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        ${{matrix.install}}
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}}  \
              -DCMAKE_CXX_STANDARD=${{matrix.std}}  \
              $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}} -- -j2

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C ${{matrix.build_type}}
      env:
        CTEST_OUTPUT_ON_FAILURE: True
